### ISSUE TITLE
`files/page.JPEG` and `files/style_samples/00` missing

### ISSUE THREAD

**Issue by madziejm** [EDM-Research/VATr-pp#1]
Can you please provide information on how to get the mentioned files?

They're referenced in the following locations in the code:

* https://github.com/EDM-Research/VATr-pp/blob/a6cd851c71f04d21e38f719cbe135572d424de23/create_style_sample.py#L8
* https://github.com/EDM-Research/VATr-pp/blob/a6cd851c71f04d21e38f719cbe135572d424de23/generate.py#L10

I cannot access the ["Pretraining dataset" Google Drive link](https://drive.google.com/drive/folders/1Xs_rR0EWt09-K6vmlvAI8pwsrmHSknC8?usp=share_link) you mention in the readme. In case this where I should look for the files, can you please make it publicly available?

Many thanks!

**Comment by BVanherle** [comment]
Hi, 

The **create_style_sample.py** file extracts the needed style samples to recreate an author's style from a page containing written words. The "files/page.JPEG" file is the input image from which it will get these style samples. I have added a command line interface for this file so that you can specify the input image and output folder.
a32d6fd39d74fecbc3c99dcbcfc397c17fc9fc32

In **generate.py**, the folder **'files/style_samples/00** contains the style samples that will be used to generate an author's handwriting, e.g. a couple of images containing words written by that author. The **create_style_sample.py** script can generate these or you can create these manually by creating some images written by an author.

I have updated the link to the pre-training dataset.
9666cdb4b75a4e714d6c2ba2e164ce4d84639608

Thanks for pointing out these issues!
